[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "bottom gentle expire inhale hat portion cat elephant guard produce pelican violin print crystal happy humor spring antique alone also fossil evil wink depart"

